Feature/assault validation
FAForever/gw-backend pull request #13
Opened 2017-08-19 21:37 UTC by 7Z0nE

implemented missing-feature #3
A faction can reach a planet, if it's solar system is connected to at least one solar system owned uniquely by that faction.
Also added tests for all involved features.
Since this is my very first (small) contribution, *feedback is highly appreciated*.

2017-08-20 11:51 UTC, Brutus5000 requested changes

2017-08-20 11:51 UTC, Brutus5000 commented on src/main/java/com/faforever/gw/model/ValidationHelper.java
> +        if (!planet.getSolarSystem().isReachable(character.getFaction())) {
This is not the only condition. The planet is also reachable if one of the other planets in the same solar systems is owned by the character's faction.

2017-08-20 11:51 UTC, Brutus5000 commented on src/main/java/com/faforever/gw/model/SolarSystem.java
> +        for (SolarSystem system : getConnectedSystems()) {
please add a note above that this approach only works with bidirectional links (just so we don't forget it later)

2017-09-18 14:24 UTC, Brutus5000 commented
@7Z0nE Are you intending to implement the missing check (see my comment) or shall I merge your PR as is and leave the issue open?

2017-09-18 14:44 UTC, 7Z0nE commented
I think I already did. See commit https://github.com/FAForever/gw-backend/commit/ecaac87541e544aa80bf009c10360321d9761c3b

2017-09-18 16:50 UTC, merged